version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    container_name: server-side

  client:
    build:
      context: ./client
    ports:
      - "5000:5000"
    container_name: client-side
    stdin_open: true
